policies:
  - name: KerasPolicy
    epochs: 150
    max_history: 3
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 3
  - name: FormPolicy

